using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Raisins.Client.Web
{
    public class Templates
    {
        public const string EMAIL =
@"
<strong>raisins autogenerated tickets</strong>

<p>
{0}
</p>

Thank you for support Jam for Hungry Minds.

";

    }
}